apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ollama.fullname" . }}-models
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.ollama.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.ollama.persistence.size }}
